package app.model;

public enum LootType {
  TRADE_GOOD, WEAPON, ARMOR, GEAR, SPECIAL, TOOL, CLOTHING, PROVISION, MOUNT, TRANSPORT, POTION, RING, ROD, SCROLL, STAVE, WAND, WONDROUS, INTELLIGENT, CURSED, ARTIFACT;
}
